### ISSUE TITLE
River Raid and Frostbite have 'jumps' in objects

### ISSUE THREAD

**Issue by sa666666** [DirtyHairy/stella#18]
I'm grouping these both together, since they both seem to be the same issue (and if I had to guess, related to player1).

In River Raid, after you play through to the first bridge and pass to the second screen, occasionally the 'house' on the left of the screen will jump horizontally.

In Frostbite, occasionally the ice-pans will jump in a similar fashion.  When using debug colours, it is P1 in both cases.

Note that these also occur in 6502.ts.

**Comment by DirtyHairy** [comment]
I think that this is the same issue as #2 and maybe even #1. In a nutshell, the emulation of `res[pmb]` is not correct on a 'microscopic' level. The net result on the counters is OK, but the emulation of the clocking delays seems to be incorrect, and this shows in edge cases where the positioning registers are strobed during hblank (this is why the effects are only visible when objects are close to the left edge of the screen).

I have tried to nail the problem, and driving the delays with different clock fixes some of the issues, but I have yet to find and understand the magic forumula that fixes everything and doesn't introduce any new issues. In particular, I still have problems interpreting Andrew Towers' notes on this, and what they describe doesn't seem to match how things are done in either the new or the old core.

This will have to wait until I have access to real hardware and an improved 6502.ts debugger (conditional breakpoints and machine events).

**Comment by sa666666** [comment]
Would the debugger in Stella be useful (it has conditional breakpoints, etc)?

Also, do we still go ahead with the test releases now, or wait until after you've had time to research this further?  If you want to do the test releases now, just create a tag as you've mentioned in a previous email, and I'll be ready to create builds for it.

**Comment by DirtyHairy** [comment]
If we get the debugger in Stella going, that'd definitely help, too. However, I find the scripting enviroment easier to work with when debugging the emulator.

From my end, I don't see any issues with starting test releases now. Among other things, ee need to get this fixed before switching to the new core by default, but I think the glitch is very minor, and I would very much like to find out about other, more straightforward to fix issues like #17 :smirk: I'll create a tag and release later today.

**Comment by DirtyHairy** [comment]
Closed for now by 839ba71 . It seems that positioning is yet of by during another clock if it happens during an extended hblank. It would be highly desirable to understand better what's happening here, though.
