### ISSUE TITLE
RESP1 artifacts in Missile Command

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#21]
At the bottom of the base P1 is displayed. 

There is a RESP1 in this line. The first copy (there is only one) shouldn't show, but it does in the new core and Stellarator.

**Comment by DirtyHairy** [comment]
That's interesting --- I have checked missile command before, but failed to identify this as an artifact :smiley:. I am very curious what causes this. If there is a RESP1 in this line, the this must be the consequence of some badly handled overlap between RESP1, the draw counter decode and the write to NUSIZ.

**Comment by DirtyHairy** [comment]
Fixed in 48d9076 .
