### ISSUE TITLE
Strawberry Shortcake - REFP0 wrong delay - vertical line of player sprite missing

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#26]
Not sure what's the cause, but the positioning of P0 or P1 seems off by one pixel.

**Comment by DirtyHairy** [comment]
That one is interesting. I don't think that it is the positioning that is wrong, but there actually is a vertical line of sprite data missing. However, the effect is not sensitive to the GRP write delay.

**Comment by thrust26** [comment]
You are right. The effect is coming from REFP0. P0 is positioned at 69 (..76), the write to REFP0 happens at cycle 48 (position 76). So there seems to be a delay missing for REFP0.

**Comment by DirtyHairy** [comment]
Thanks alot :smirk: b3c0993 fixes this by introducing a delay of one clock.
