### ISSUE TITLE
Yar's Revenge sometimes crashes with "invalid width" exception

### ISSUE THREAD

**Issue by sa666666** [DirtyHairy/stella#27]
Yar's Revenge sometimes fails to start with exception "invalid width" being thrown. Sometimes this is caught in the ROM launcher and displayed, but sometimes the emulator outright crashes. Other times, the ROM starts for a second or two, only to crash a little later. This exception is thrown only in the Player class, so something is screwy there.

Note, this **doesn't** occur in Stellerator.

**Comment by sa666666** [comment]
Yar's Revenge sometimes fails to start with exception "invalid width" being thrown.  Sometimes this is caught in the ROM launcher and displayed, but sometimes the the emulator outright crashes.  Other times, the ROM starts and plays normally.  This exception is thrown only in the Player class.

**Comment by DirtyHairy** [comment]
Fixed in f360e7f .
