### ISSUE TITLE
Yahtzee dice are jumping vertically

### ISSUE THREAD

**Issue by sa666666** [DirtyHairy/stella#28]
The dice in Yahtzee seem to be drawn at different lines (30 Hz flicker).  One set is in the right place, and the other set is moved downwards.  This also happens in Stellerator.

Note that the behaviour of this ROM is improved from the old core, where there was a die being drawn to the extreme left.  So we have a fix and a regression :)

**Comment by DirtyHairy** [comment]
Fixed by frame manager improvements. Basically, there are two types of frames, one with text, the other without text, and both had different detected ystart / vblank values. The visual impression was that of the dices jumping above static text.
