### ISSUE TITLE
BLNKTEST.BIN doesn't show 'combed' columns

### ISSUE THREAD

**Issue by sa666666** [DirtyHairy/stella#29]
This test ROM should show combs for the columns, instead of straight edges.  Attached is the ROM with a picture of the correct behaviour from the old Stella core.

[BLNKTEST.zip](https://github.com/DirtyHairy/stella/files/641128/BLNKTEST.zip)
![blnktest](https://cloud.githubusercontent.com/assets/16061066/21036594/931492e2-bda1-11e6-8ccf-d2dc864397cd.png)

**Comment by DirtyHairy** [comment]
Fixed in 18c31eb by introducing a delay of 1 clock to vblank. For future reference I have created an extended testcase that allows to discriminate between VBLANK and COLUBK lines via color [here](https://github.com/6502ts/6502.ts/tree/master/aux/2600/blnktest_ext).
