### ISSUE TITLE
Title Match Pro Wrestling - Early RESM0 or wide missiles?

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#30]
At the scoreboard, part of the left board, which is created by the 3rd copy of an 8 pixel wide missile (6 pixel hidden behind PF) is one pixel to narrow. It seems that the missile is positioned one pixel too far to the left. 

The positioning is done with RESM0 ending at cycle 25.

**Comment by DirtyHairy** [comment]
Interesting. The RESM0 happens during an extended hblank, so this may very well be the same bug as #2 and #18 . One bug to rule them all, one bug to find them...

**Comment by DirtyHairy** [comment]
Fixed for now by 839ba71
