### ISSUE TITLE
Frostbite ice-pans not forming correctly

### ISSUE THREAD

**Issue by sa666666** [DirtyHairy/stella#33]
In a level where the ice-pans separate (starts at level 4), they are not being positioned correctly.  To see what I mean, look at the following snapshots in debug mode.

For the first one, I've paused and taken the snapshot just as the pans touch (which is where they should stop):
![frostbite 1983 activision _1](https://cloud.githubusercontent.com/assets/16061066/21182280/cbf58258-c1dc-11e6-89d8-3df89bb9edfb.png)

When I unpause, you can see that the pans continue to move together, and form a smaller pan than normal (they overlap, when they should _just_ touch):
![frostbite 1983 activision _2](https://cloud.githubusercontent.com/assets/16061066/21182281/cbf6d464-c1dc-11e6-8da8-47afbbde7d82.png)

When the pans fully open, you can see that they aren't evenly spaced (there should be 6 small pans, all positioned equal distance from the next one):
![frostbite 1983 activision _3](https://cloud.githubusercontent.com/assets/16061066/21182284/cbf8583e-c1dc-11e6-86e9-d1295ac4b170.png)

The following two are snapshots from the old core, showing the proper behaviour:
![frostbite 1983 activision _4](https://cloud.githubusercontent.com/assets/16061066/21182283/cbf7795a-c1dc-11e6-94a9-68efaf447eaa.png)
![frostbite 1983 activision _5](https://cloud.githubusercontent.com/assets/16061066/21182282/cbf73ec2-c1dc-11e6-88c6-13c98d4906a4.png)

P1 and M1 are affected; either one is moving too far to the left, or the other too far to the right (or both!).

**Comment by DirtyHairy** [comment]
Fixed in a982a33 --- this was due do slightly wrong RESMP positioning for 8 pixel players. The issue was already visible with wide ice pans (overlap where there shouldn't be any) and small ice pands (spacing). However, I suck at Frostbite :white_flag: , and getting to a level with separating ice pans seems above me, so please doublecheck and reopen if there are still issues.

**Comment by sa666666** [comment]
Tested again, and everything is fine now.
