### ISSUE TITLE
Very minor speed difference

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#35]
Between the old core and the new core, there is a (very) small speed difference. If you run e.g the title screen of Marble Craze in parallel on both cores (VSync enabled), you will find that pre2 is slightly faster. The difference is a bit more noticeable in the PAL version.

I don't think this is worth a fix, but maybe it can be used as an indicator for other differences.

[Marble Craze.zip](https://github.com/DirtyHairy/stella/files/652532/Marble.Craze.zip)

**Comment by DirtyHairy** [comment]
I am pretty sure that this is a direct consequence of #10: currently, timing is based on frame rate solely, and this can lead to considerable differences if the frame size is off. I've seed this effect in several other ROMs as well, but cannot list them from memory :smirk:

**Comment by sa666666** [comment]
This is definitely because of https://github.com/DirtyHairy/stella/issues/10.  The NTSC ROM runs at 264 scanlines but still shows 60Hz.  The Hz should be slightly lower, but I haven't gotten to fixing it yet.  Once that is fixed, the framerate will decrease a little and run as normal.

**Comment by sa666666** [comment]
Fixed in https://github.com/DirtyHairy/stella/commit/e618a6c72c7ca9abd4e34cb3a38c6e485430e87b.
