### ISSUE TITLE
Meltdown - double sized copies with wrong positioning

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#36]
The right two rods do flicker not together correctly. 

Reason: The non-reflected copy displays 1 pixel too far left, the reflected copy 1 pixel too far right.

**Comment by DirtyHairy** [comment]
Thanks for the pointer in the right direction. The conclusion that I draw from debugging is the following:

Even and odd frames are shifted relative to each other by one pixel in order to get nice circles. It seems that, similar to RESPx during draw counter decode, there are side effects of NUSIZx during draw counter decode on the decode circuit, leading to a delay on each odd frame. In fact, you can see that the code tries to compensate for that by shifting GRPx by one pixel to the right when drawing the second copy.

In d77d2f2, I have tries to model this delay, and the result looks pretty much perfect to me
![meltdown 1983 20th century fox prototype](https://cloud.githubusercontent.com/assets/2444224/21289276/07608ce8-c499-11e6-939e-e6ed60d4545b.png)

As I cannot compare yet to real hardware (and can't find any footage of the real thing out there on the web), I have built a windows test binary 
[stella_e618a6c_test.zip](https://github.com/DirtyHairy/stella/files/659044/stella_e618a6c_test.zip)
However, this is crosscompiled from linux using mingw, so it is pretty limited and should really be only used for testing --- in particular, it needs `-video software`, doesn't support joysticks and is build with `-O0` :smirk:

**Comment by thrust26** [comment]
That download doesn't work for me (crash). And without joystick, I cannot test well anyway.

The screenshot looks OK, but you can check your solution yourself:
1. The top cursor is aligned identical above all four columns 
2. IIRC MESS emulates Meltdown correctly

**Comment by DirtyHairy** [comment]
Hmm, too bad. With 'without joystick', I meant 'without gamepad / joystick' support; of course, the cursor keys work fine, at least in wine. Too bad it doesn't work on real windows.

Cursor alignment is interesting; it *is* different between the four columns, but funnily, the rightmost ones look correct to me. I'll crosscheck with MESS.

**Comment by thrust26** [comment]
Can you make screenshots with the cursor being on the left and right?

**Comment by DirtyHairy** [comment]
Here you go.
![meltdown 1983 20th century fox prototype](https://cloud.githubusercontent.com/assets/2444224/21289417/e7e15096-c49d-11e6-9a96-91a4baf7ba5f.png)
![meltdown 1983 20th century fox prototype _1](https://cloud.githubusercontent.com/assets/2444224/21289420/e7e39e1e-c49d-11e6-854d-eb53270094af.png)
![meltdown 1983 20th century fox prototype _2](https://cloud.githubusercontent.com/assets/2444224/21289419/e7e3493c-c49d-11e6-900a-ca65a210ad60.png)
![meltdown 1983 20th century fox prototype _3](https://cloud.githubusercontent.com/assets/2444224/21289418/e7e2b706-c49d-11e6-8171-4607f1eb8a6b.png)

**Comment by DirtyHairy** [comment]
![meltdown 1983 20th century fox prototype](https://cloud.githubusercontent.com/assets/2444224/21289427/0ed3b784-c49e-11e6-9359-9d275b5414ef.png)
![meltdown 1983 20th century fox prototype _1](https://cloud.githubusercontent.com/assets/2444224/21289425/0ed328aa-c49e-11e6-99c5-034936647573.png)
![meltdown 1983 20th century fox prototype _2](https://cloud.githubusercontent.com/assets/2444224/21289428/0ed624d8-c49e-11e6-9e4a-03bd41e06559.png)
![meltdown 1983 20th century fox prototype _3](https://cloud.githubusercontent.com/assets/2444224/21289426/0ed36388-c49e-11e6-9316-4b8f35bb5a53.png)

**Comment by DirtyHairy** [comment]
Also, interestingly, the four columns are equistant already, so any error should likely be a total shift.

**Comment by thrust26** [comment]
All rods look shifted by one pixel to the right.

**Comment by DirtyHairy** [comment]
OK, next try, I indead have found a typo I made when fixing Missile Command. Fixing this has now shifted the left rods one pixel to the left. Do you still think the right rods should also be shifted by one pixel to the right (currently, they are not strictly equidistant any more)?

![meltdown 1983 20th century fox prototype](https://cloud.githubusercontent.com/assets/2444224/21289528/b1c331bc-c49f-11e6-9275-415f33656ea4.png)
![meltdown 1983 20th century fox prototype _1](https://cloud.githubusercontent.com/assets/2444224/21289531/b1c54240-c49f-11e6-900e-e401c2ed49f9.png)
![meltdown 1983 20th century fox prototype _2](https://cloud.githubusercontent.com/assets/2444224/21289530/b1c4610e-c49f-11e6-9cec-84addbfed2c1.png)
![meltdown 1983 20th century fox prototype _3](https://cloud.githubusercontent.com/assets/2444224/21289529/b1c3e756-c49f-11e6-8ba0-e594e7aab318.png)

**Comment by thrust26** [comment]
Assuming the old core is correct here, the cursor is at 28, 61, 92, 125. Since on real hardware all rods are aligned identical to the cursor, this means that the gap between column 2 and 3 is different.

**Comment by DirtyHairy** [comment]
Still another try. The gap between 2 and 3 is now noticably different, but the cursor is really the same for all columns
![meltdown 1983 20th century fox prototype](https://cloud.githubusercontent.com/assets/2444224/21289601/87ffa9e4-c4a1-11e6-8c8d-4690dc7f7f4f.png)
![meltdown 1983 20th century fox prototype _1](https://cloud.githubusercontent.com/assets/2444224/21289602/87ffe18e-c4a1-11e6-8c7c-9138c1864df5.png)
![meltdown 1983 20th century fox prototype _2](https://cloud.githubusercontent.com/assets/2444224/21289603/8801f2ee-c4a1-11e6-9ec1-197ac4b870c3.png)
![meltdown 1983 20th century fox prototype _3](https://cloud.githubusercontent.com/assets/2444224/21289604/88036886-c4a1-11e6-82a4-aedc86e246e6.png)



. What do you think?

**Comment by thrust26** [comment]
Looks correct now.

**Comment by DirtyHairy** [comment]
Great :smirk: I'll crosscheck with MESS once it has finished compiling and will close the ticket after that. Thanks for your time, Thomas.

**Comment by DirtyHairy** [comment]
39ee43e matches MESS.

**Comment by sa666666** [comment]
Thomas, here is a Windows build for you to test the latest changes:
    http://minbar.org/Stella-5.0.0-pre2.5-windows.zip

Also, **HOLY CRAP**.  This last commit or two fixes the rendering issues in "Mega Bitmap Demo", which I've never seen work in _any_ emulator up to this point!  See the following snapshots.

From the old core, where it was completely broken:
![atext_oldcore](https://cloud.githubusercontent.com/assets/16061066/21290726/d66d3d32-c49f-11e6-81f8-2f05678fef0c.png)

From MESS, which was the closest so far:
![atext_mess](https://cloud.githubusercontent.com/assets/16061066/21290724/d669df7a-c49f-11e6-8740-273f1c803fe4.png)

With the most current code:
![atext_newcore](https://cloud.githubusercontent.com/assets/16061066/21290725/d66a5c8e-c49f-11e6-989a-c1c77923308e.png)

**Comment by thrust26** [comment]
Yay! :)

**Comment by DirtyHairy** [comment]
🤘Even on 6502.ts, and even on my mobile (that's where I just tested it).

**Comment by thrust26** [comment]
BTW: The 32 character demos are all working correctly with the new core too.

http://atariage.com/forums/topic/180632-32-character-text-display
