### ISSUE TITLE
ENABL delay too small

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#39]
The colon between minutes and seconds is corrupted. The right pixel is enabled and disabled ~1/3 cycle too early.
[Super Challenge Football (1982) (Mattel).zip](https://github.com/DirtyHairy/stella/files/659413/Super.Challenge.Football.1982.Mattel.zip)

**Comment by DirtyHairy** [comment]
Indeed, it seems we need a delay there. Fixed in b700149 . I also included a corresponding delay for "delayed ENABL" (triggered by a write to GRP1) --- I thought this was the reason, but it wasn't. Anyway, the players have one there, too, so I guess it should've been there all along :smirk:

**Comment by DirtyHairy** [comment]
![super challenge football 1982 m network](https://cloud.githubusercontent.com/assets/2444224/21293892/7e15cbcc-c530-11e6-988b-5cfa50e8eecc.png)
