### ISSUE TITLE
Debugger error: mirrored addresses not complete

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#41]
Note: Unrelated to new code (kill me, if I shouldn't post this here :))

Some mirror seem to be missing, e.g. trapreadm INPT4 does not catch INPT4|$30

**Comment by sa666666** [comment]
Confirmed; when setting TIA addresses, I considered only the mirrors for write (0-3F), not for read (0-F).  So for INPT4, the addresses set are 0C, 4C, etc, when they should be 0C, 1C, 2C, 3C, ...

**Comment by thrust26** [comment]
Why are you using extra commands for mirrored addresses anyway? I cannot see any case where I would prefer to use non-mirrored traps. Do you?

**Comment by sa666666** [comment]
The original trap commands, added with the initial debugger support (sometime around 3.0) were the non-mirrored versions.  Why I didn't add the mirrored ones from the very beginning, I cannot say.  WHen I added the mirrored versions in the last release (4.7.3), I didn't want to break compatibility with what was already there, so I added a new set of commands.

**Comment by sa666666** [comment]
Fixed in https://github.com/DirtyHairy/stella/commit/07287fe76141c9260176201a690bc9c53c8e0411.
