### ISSUE TITLE
Colored Wall Demo (PD)

### ISSUE THREAD

**Issue by sa666666** [DirtyHairy/stella#47]
![colored wall demo pd](https://cloud.githubusercontent.com/assets/16061066/21369186/53e1dad8-c6e0-11e6-9cc1-f3b50aa325a4.png)

![colored wall demo pd _1](https://cloud.githubusercontent.com/assets/16061066/21369187/57b6f2a6-c6e0-11e6-9687-f00e6b9a5f1e.png)

Although the results are worse in the new core, they are consistent with real hardware.

**Comment by thrust26** [comment]
Where did you get that ROM? Looks a bit like my Rubik's Cube attempts.

**Comment by sa666666** [comment]
Not sure, but I think from some archive on AtariAge.  I have literally thousands of ROMs here, so I forget where many of them came from.
