### ISSUE TITLE
32 char DPC+ demo

### ISSUE THREAD

**Issue by sa666666** [DirtyHairy/stella#52]
![32_20120625](https://cloud.githubusercontent.com/assets/16061066/21369976/259fba10-c6e4-11e6-9a02-dda3e1cf1763.png)

![32_20120625_1](https://cloud.githubusercontent.com/assets/16061066/21369977/25a5bfdc-c6e4-11e6-80b4-3b56b20bb479.png)

Text should be contained in the center area, not spill into the left-most black area.

**Comment by thrust26** [comment]
@sa666666 @DirtyHairy 

I suggest in case of non original game ROMs, we add the ROMs here too.

**Comment by DirtyHairy** [comment]
That's I good idea --- some of these ROMs exist in multiple different iterations on the forums :smirk:
