### ISSUE TITLE
36 char demo (eshu)

### ISSUE THREAD

**Issue by sa666666** [DirtyHairy/stella#53]
![36char](https://cloud.githubusercontent.com/assets/16061066/21370067/8e0eb84e-c6e4-11e6-8053-c26890eaa5f7.png)
![36char_1](https://cloud.githubusercontent.com/assets/16061066/21370068/8e300a4e-c6e4-11e6-8cb3-702f6aa3197b.png)

Another case where the results from the old core look better, but the new core accurately emulates real hardware.

**Comment by thrust26** [comment]
ROM added
[36 char demo (Eshu).zip](https://github.com/DirtyHairy/stella/files/666690/36.char.demo.Eshu.zip)
