### ISSUE TITLE
Snoopy and the Red Baron - RESMPx problem

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#60]
It seems like the missiles are positioned (at least) one pixel too far right. Both missiles are initially once positioned using RESMPx and then, (like the players too) only by using HMOVE.

More details [here](http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-2#entry3654686).

**Comment by DirtyHairy** [comment]
The obvious fix would be an adjustment to the RESMPx offset. However, this also affects Eshus paranoid demo which *seems* to be correct with the current value. However, I am not sure how this compares to real hardware, so I will wait with this change until I have found time to run some RESPMx tests on real hardware. My harmony has arrived, so that's gonne be soonish :smile: :fireworks:

**Comment by thrust26** [comment]
I am pretty sure it is one pixel too wide. When you move it to the very right, rhe rightmost pixel wraps around in new core but not in real hardware.

**Comment by DirtyHairy** [comment]
I agree; I just compared to MESS, and it also seems to have the paddle one pixel shorter. I have commited the change as cbb3c46 --- let's revisit this if similar issues come up :smirk:

**Comment by DirtyHairy** [comment]
For reference, this is how Snoopy looks now:

![snoopy and the red baron 1983 atari](https://cloud.githubusercontent.com/assets/2444224/21407177/9058e8d6-c7cf-11e6-8d6d-825b89897caa.png)

and that is paranod:

![paranoid_0 01_real_1](https://cloud.githubusercontent.com/assets/2444224/21407189/9cd7500c-c7cf-11e6-9645-3807e28dc37c.png)

**Comment by thrust26** [comment]
MESS emulates pretty well, doesn't it?

**Comment by DirtyHairy** [comment]
Yes, it wasn't on my radar before you mentioned it in the context of Meltdown, but it actually is pretty good.

**Comment by DirtyHairy** [comment]
Btw, how do you move the paddle in paranoid?

**Comment by thrust26** [comment]
With paddle controllers.

**Comment by DirtyHairy** [comment]
Ouch. You're right :see_no_evil: Sometimes, it's the thing with the forest through the trees...
