### ISSUE TITLE
Spike's Peak - Early HMBL after HMOVE

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#62]
There is a too early HMBL after HMOVE right below the mountain. On real hardware and in the old core, this creates a gap in the path on the left and a one pixel overlapping on the right. The new core doesn't have that gap and overlapping.

Hardware:
![spike s peak 1983 xonox](https://cloud.githubusercontent.com/assets/24360774/21401397/8f5cbd6a-c7b4-11e6-96f5-da9940b55389.png)

Since Pre2: 
![spike s peak 1983 xonox _2](https://cloud.githubusercontent.com/assets/24360774/21401492/d79ec848-c7b4-11e6-982d-aa3532366d60.png)

**Comment by DirtyHairy** [comment]
Fixed in 0d37bbe . This actually was a side effect of my starfield effect implementation: in this line, the ball goes into 'starfield mode', and the core moved it one pixel to the left. As @thrust26 , this movement doesn't apply to objects of width 4 or more -> fixed.

**Comment by thrust26** [comment]
Pretty cool side effect. :)
