### ISSUE TITLE
Sprite toggling for debugging

### ISSUE THREAD

**Issue by DirtyHairy** [DirtyHairy/stella#9]

**Comment by DirtyHairy** [comment]
Done in a717890c2

**Comment by thrust26** [comment]
@DirtyHairy You missed toggling HMOVE blanks (ALT+M)

**Comment by DirtyHairy** [comment]
Actually, this was on purpose: the new core works differently, and there is not much to see during hmove blanks, and if you did, it would look pretty different from the old core. Afaik, Stephen intends to completely remove this option :smirk:

**Comment by thrust26** [comment]
Makes sense.
